---
title: "Εισαγωγή"
subtitle: "1ο μάθημα"
author: "Αλέξανδρος Ρέκκας"
date: today
format:
  revealjs:
    theme: [default, custom.scss]
    slide-number: true
    logo: logo.png
    footer: ""
    lang: el
    incremental: false
    font-size: 32px
execute:
  echo: false
---

## Με τι ασχολείται η οικονομετρία;

- Έλεγχος οικονομικών θεωριών
- Πρόγνωση μελλοντικών τιμών μεταβλητών
- Εκτίμηση μοντέλων με τη χρήση πραγματικών δεδομένων
- Χρήση ιστορικών δεδομένων για το σχεδιασμό πολιτικών

## Παραδείγματα

> **Παράδειγμα 1**
>
> _Μικρότερα τμήματα οδγούν σε καλύτερες επιδόσεις στο δημοτικό σχολείο;_

\

- Το κάθε παιδί παίρνει περισσότερη από την προσοχή του δασκάλου
- Μείωση μεγέθους σημαίνει περισσότερα τμήματα
- Σημαίνει πρόσληψη περισσότερων δασκάλων
- Τα οφέλη ξεπερνούν το κόστος;

## Παραδείγματα

> **Παράδειγμα 2**
>
> _Υπάρχουν φυλετικές διακρίσεις στην αγορά των στεγαστικών δανείων;_

\

Μία μελέτη βρήκε ότι:

- Οι αιτήσεις μεταναστών έχουν 20% πιθανότητα να απορριφθούν.
- Οι αιτήσεις των ντόπιων εχουν πιθανότητα 10% να απορριφθούν.

\

> Τι ισχύει για αιτήσεις που κατά τα άλλα είναι ίδιες;

## Παραδείγματα

> **Παράδειγμα 3**
>
> _Βελτιώνει η αύξηση δαπανών για την υγεία τα κλινικά αποτελέσματα ενός πληθυσμού;_

\

- Κατά πόσο η αύξηση υγειονομικών δαπανών μειώνει την αποτρέψιμη θνησιμότητα;
- Πόσο πρέπει να αυξηθούν οι οικονομικές δαπάνες για να επιτευχθούν οι επιθυμητοί στόχοι;

## Αιτιότητα

\

Στα προηγούμενα ερωτήματα το ζητούμενο ήταν η αξιολόγηση αιτιακών σχέσεων

\

> **Αιτιότητα**
>
> _Μία συγκεκριμένη δράση προκαλεί ένα συγκεκριμένο και μετρήσιμο αποτέλεσμα._


## Αιτιότητα

\

Η διερεύνηση των αιτιακών σχέσεων πραγματοποιείται με _τυχαιοποιημένες ελεγχόμενες δοκιμές_.

\

> **Ερώτημα:**
>
> Το εμβόλιο της γρίπης προστατεύει από την εκδήλωση της ασθένειας;

## Παραδείγματα

> **Παράδειγμα 4**
>
> _Πόσο θα είναι το ΑΕΠ της χώρας τον επόμενο χρόνο;_

\

- Στόχος είναι η πρόγνωση (forecast) της τιμής του ΑΕΠ στο μέλλον
- Με βάση αυτή τη γνώση μία συμβουλευτική εταιρία μπορεί να προτείνει ή να
  αποτρέψει έναν πελάτη της να επενδύσει.


## Αιτιότητα;


- Η πρόγνωση (forecast) είναι πρόβλεψη (prediction) στο μέλλον.
- Δεν απαιτεί τη γνώση των αιτιακών σχέσεων.

\

> **Παράδειγμα**
>
> Προβλέπουμε την πιθανότητα ενός ανθρώπου να εκδηλώσει καρκίνο στους πνεύμονες
> από το αν έχει πάνω του αναπτήρα.

\

Συνήθως, η πρόγνωση στηρίζεται σε μεταβλητές που εξελίσσονται χρονικά

## Δεδομένα

\

Μιλάμε για δύο γενικές κατηγορίες δεδομένων που χρησιμοποιούνται στην οικονομετρία:

- Τα πειραματικά δεδομένα
- Τα δεδομένα παρατήρησης

## Δεδομένα

\

Υπάρχουν τρεις βασικοί τύποι δεδομένων:

- Διαστρωματικά ή συγχρονικά δεδομένα (cross-sectional data).
- Δεδομένα χρονικής σειράς ή χρονοσειράς (time-series data).
- Διαστρωματικές χρονοσειρές ή δεδομένα πάνελ (panel data)


## Διαστρωματικά δεδομένα

\

> **Ορισμός**
>
> Δεδομένα για τους εργαζόμενους, εταιρίες, κυβερνητικούς οργανισμούς σε μία
> συγκεκριμένη χρονική στιγμή.

\

**Παράδειγμα:**

- Οι δαπάνες των χωρών της ΕΕ για την υγεία το 2020.
- Τα ποσοστά ανεργίας, ο πληθωρισμός και η αύξηση του ΑΕΠ παγκοσμίως το 2025.

## Δεδομένα χρονοσειράς

\

> **Ορισμός**
>
> Δεδομένα για μία οντότητα που συλλέχθηκαν σε διαφορετικές χρονικές στιγμές.

\

**Παράδειγμα:**

- Το ΑΕΠ μίας χώρας ανά τρίμηνο.
- Η αξία μίας μετοχής ανά ημέρα.
- Η ισοτιμία του ευρώ με το δολλάριο κάθε ημέρα.

## Δεδομένα διαστρωματικής χρονοσειράς

\

> **Ορισμός**
>
> Δεδομένα για πολλές οντότητες που συλλέχθηκαν σε διαφορετικές χρονικές στιγμές.

\

**Παράδειγμα:**

- Το ετήσιο εισόδημα 1000 νοικοκυριών της χώρας τα τελευταία 10 χρόνια.

# Γραμμική παλινδρόμηση

## Εισαγωγή

\

> Ο διευθυντής ενός δημοτικού σχολείου σκέφτεται να προσλάβει περισσότερους δασκάλους.
>
> Σας ζητά να υπολογίσετε το όφελος του να χωρίσει τις τάξεις στα 2.

\
\

> Ένας γονιός θέλει να μετακομίσει σε νέα γειτονιά.
> 
> Σας ζητά να προβλέψετε τις σχολικές επιδόσεις της νέας γειτονιάς με βάση το
> μέγεθος των τάξεων.

## Πρόβλεψη

Προβλέπουμε την τιμή $Y_i$ για μια παρατήρηση του δείγματος $X_i$ από τη σχέση:

$$
\hat{Y}_i=\hat{\beta}_0 + \hat{\beta}_1X_i
$$

- Η πρόβλεψη αυτή ονομάζεται πρόβλεψη εντός δείγματος (in-sample prediction).
- Πιο πολύ μας ενδιαφέρει η πρόβλεψη εκτός δείγματος (out-of-sample prediction).

\

Πιο συγκεκριμένα, για ένα νέο $\tilde{X}_j$ προβλέπουμε την (πραγματική) τιμή $\tilde{Y}_j$ από:

$$
\hat{Y}_j=\hat{\beta}_0 + \hat{\beta}_1\tilde{X}_j
$$

## Πρόβλεψη

- Το $\tilde{Y}_j$ δεν είναι γνωστό.
- Η πρόβλψη πρέπει να πλαισιωθεί από ένα σφάλμα.

Μια απλή προσέγγιση είναι να προβλέψουμε το $\tilde{Y}_j$ ως $\hat{Y}_j\pm s_{\hat{u}}$
